protected/models/Player.php
<?php
/**
 *
 *   Copyright © 2010-2019 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/

class Player extends ActiveRecord
{
/*
    int $id
    string $server_id
    string $name
    int $level
    string $lastseen
    string $banned
    string $op
    string $status
    string $ip
    string $previps
    string $quitreason
*/

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function getDbConnection()
    {
        return Yii::app()->bridgeDb;
    }

    public function tableName()
    {
        return 'player';
    }

    public function rules()
    {
        return array(
            array('name', 'required'),
            array('name', 'checkName'),
            array('name', 'filter', 'filter' => 'trim'),
            array('level', 'numerical', 'integerOnly'=>true),
            array('name, banned', 'length', 'max'=>128),
            array('server_id', 'numerical', 'on'=>'superuser'),
            array('id, server_id, name, level, lastseen, banned, op, ip', 'safe', 'on'=>'search'),
            array('name, level, lastseen, banned, op, ip', 'safe', 'on'=>'serverSearch'),
            array('server_id', 'unsafe', 'on'=>'serverSearch'),
        );
    }

    public function checkName($attribute, $params)
    {
        $other = $this->findAllByAttributes(array('name'=>$this->name, 'server_id'=>$this->server_id));
        if (!count($other))
            return;
        if (count($other) > 1 || $other[0]->id != $this->id)
            $this->addError('name', Yii::t('mc', 'This name is already in use by another player.'));
    }

    public function relations()
    {
        return array(
            'server' => array(self::BELONGS_TO, 'server', 'server_id'),
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('mc', 'ID'),
            'server_id' => Yii::t('mc', 'Server'),
            'name' => Yii::t('mc', 'Name'),
            'level' => Yii::t('mc', 'Role'),
            'lastseen' => Yii::t('mc', 'Last Seen'),
            'banned' => Yii::t('mc', 'Banned'),
            'op' => Yii::t('mc', 'Op'),
            'status' => Yii::t('mc', 'Status'),
            'ip' => Yii::t('mc', 'IP'),
            'previps' => Yii::t('mc', 'Previous IPs'),
            'quitreason' => Yii::t('mc', 'Last Quit Reason'),
        );
    }

    public function search()
    {
        $criteria=new CDbCriteria;

        $criteria->compare('`id`',$this->id);
        $criteria->compare('`server_id`',$this->server_id);
        $criteria->compare('`name`',$this->name,true);
        $criteria->compare('`level`',$this->level);
        $criteria->compare('`lastseen`',$this->lastseen,true);
        $criteria->compare('`banned`',$this->banned,true);
        $criteria->compare('`op`',$this->op,true);
        $criteria->compare('`status`',$this->status,true);
        $criteria->compare('`ip`',$this->ip,true);
        $criteria->compare('`previps`',$this->previps,true);
        $criteria->compare('`quitreason`',$this->quitreason,true);

        return new CActiveDataProvider(get_class($this), array(
            'criteria'=>$criteria,
            'pagination'=>array('pageSize'=>20),
        ));
    }

    public function getUser()
    {
        $sql = 'select `user_id` from `user_player` where `player_id`=?';
        $cmd = Yii::app()->db->createCommand($sql);
        $cmd->bindValue(1, $this->id);
        return $cmd->queryScalar();
    }

    public function setUser($usr, $save = true)
    {
        if (!is_object($usr))
            $usr = User::model()->findByPk((int)$usr);
        if ($usr)
        {
            $sql = 'replace into `user_player` (`user_id`,`player_id`) values(?,?)';
            $cmd = Yii::app()->db->createCommand($sql);
            $cmd->bindValue(1, $usr->id);
            $cmd->bindValue(2, $this->id);
        }
        else
        {
            $sql = 'delete from `user_player` where `player_id`=?';
            $cmd = Yii::app()->db->createCommand($sql);
            $cmd->bindValue(1, $this->id);
        }
        if (!$cmd->execute())
            return false;
        if ($usr)
            $this->level = $usr->getLevel($this->server_id);
        else
            $this->level = 1;
        if (!$save)
            return true;
        return $this->save();
    }

    public function afterSave()
    {
        McBridge::get()->serverCmd($this->server_id, 'load player '.$this->id);
        return parent::afterSave();
    }

    public function afterDelete()
    {
        UserPlayer::model()->deleteAllByAttributes(array('player_id'=>$this->id));
        McBridge::get()->serverCmd($this->server_id, 'load player '.$this->id);
        return parent::afterDelete();
    }
}

protected/controllers/PlayerController.php
<?php
/**
 *
 *   Copyright © 2010-2019 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/

class PlayerController extends Controller
{
    public $layout='//layouts/column2';

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow', 
                'actions'=>array('view'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('index', 'create', 'update', 'delete', 'deleteAll',),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin',),
                'expression'=>'$user->isSuperuser()',
            ),
            array('deny',
                'users'=>array('*'),
            ),
        );
    }

    public function ajaxRefresh($player, $type)
    {
        if (@Yii::app()->params['delay_daemon_queries'] && !isset($_POST['ajax']))
            return array();
        $all = ($type === 'all');
        if (!is_array($type))
            $type = array($type);
        $ret = array();

        if ($all || in_array('tp', $type) || in_array('summon', $type))
        {
            ob_start();
            $error = '';
            if (!Yii::app()->user->can($player->server_id, 'get_players'))
                $error = Yii::t('mc', 'Permission denied.');
            else if (!McBridge::get()->serverCmd($player->server_id, 'get players', $players))
                $error = McBridge::get()->lastError();

            if (strlen($error))
                echo CHtml::encode($error);
            else
            {
                foreach ($players as $player)
                    echo CHtml::tag('option', array('value'=>$player['id'], (($player['id'] == @$defOther) ? 'selected' : '')=>'selected'), CHtml::encode($player['name']));
            }
            $ret['summon'] = $ret['tp'] = ob_get_clean();
        }
        return $ret;
    }

    private function possiblePlayerRoles($model)
    {
        $userRoles = array('1' => Yii::t('mc', 'Default Role'));
        $userRoles += array_combine(User::$roleLevels, User::getRoleLabels());
        if (!Yii::app()->user->isSuperuser())
        {
            $idx = array_search(Yii::app()->user->serverRole($model->server_id), User::$roles);
            if ($idx === false)
                $userRoles = array();
            else
            {
                $ur = $userRoles;
                $userRoles = array();
                foreach ($ur as $level=>$role)
                {
                    $userRoles[$level] = $role;
                    if ($idx-- < 0)
                        break;
                }
            }   
            if (array_search($model->level, array_keys($userRoles)) === false)
                $userRoles = array();
        }
        return $userRoles;
    }

    public function actionView($id)
    {
        $model = $this->loadModel($id);
        Yii::app()->user->canSelf($model, 'view_player', true);
        if (isset($_POST['ajax']))
        {
            switch($_POST['ajax'])
            {
            case 'give':
                if (!Yii::app()->user->canSelf($model, 'give', true))
                    die(Yii::t('mc', 'Error: Permission denied.'));
                require 'itemlist.php';
                $amount = (int)$_POST['amount'];
                $item = $_POST['item'];

                if (!@strlen($item) || !isset($itemlist[$item]))
                    die("Invalid item selected!".$item);
                else if ($amount < 0 || $amount > 64)
                    die("Invalid amount!");
                else
                {
                    $i = $itemlist[$item];
                    if (!McBridge::get()->serverCmd($model->server_id,
                            'mc:give '.$model->name.' '.$i['item'].' '.$amount.($i['data'] ? ' '.$i['data'] : '')))
                        die(Yii::t('mc', 'Error sending command:').' '.CHtml::encode(McBridge::get()->lastError()));
                }
                break;
            case 'tp':
                Yii::app()->user->canSelf($model, 'tp', true);
                $player = (int)$_POST['player'];
                $player = Player::model()->findByPk($player);
                if (!$player)
                    die(Yii::t('mc', 'Invalid target player...'));
                if (!McBridge::get()->serverCmd($model->server_id, 'mc:tp '.$model->name.' '.$player->name))
                    die(Yii::t('mc', 'Error sending command:').' '.CHtml::encode(McBridge::get()->lastError()));
                break;
            case 'summon':
                Yii::app()->user->can($model->server_id, 'tp', true);
                $player = (int)$_POST['player'];
                $player = Player::model()->findByPk($player);
                if (!$player)
                    die(Yii::t('mc', 'Invalid target player...'));
                if (!McBridge::get()->serverCmd($model->server_id, 'mc:tp '.$player->name.' '.$model->name))
                    die(Yii::t('mc', 'Error sending command:').' '.CHtml::encode(McBridge::get()->lastError()));
                break;
            case 'assign':
                $user = (int)$_POST['user'];
                $user = User::model()->findByPk($user);
                if (!$user)
                    die(Yii::t('mc', 'Invalid user selected.'));
                if (!($model->user = $user))
                    die(Yii::t('mc', 'Failed to assign user!'));
                break;
            case 'refresh':
                header('Content-type: application/json');
                echo CJSON::encode($this->ajaxRefresh($model, $_POST['type']));
            }
            Yii::app()->end();
        }

        $playerRoles = $this->possiblePlayerRoles($model);
        if(isset($_POST['Player']) && Yii::app()->user->can($model->server_id, 'manage_players'))
        {
            if (Yii::app()->user->isSuperuser())
                $model->scenario = 'superuser';
            $lvl = $model->level;
            $model->attributes=$_POST['Player'];
            if ($playerRoles)
            {
                if (array_search($model->level, array_keys($playerRoles)) === false)
                    $model->level = $lvl; //preserve level if user has no permission to change it
                $userName = Yii::app()->request->getPost('user-name', '');
                $user = User::model()->findByAttributes(array('name'=>$userName));
                if (!$user && @strlen($userName))
                    $model->addError('user', Yii::t('mc', 'User not found'));
                else if ($user && $model->user != $user->id
                        && array_search($user->getLevel($model->server_id), array_keys($playerRoles)) !== false)
                {
                    Yii::log('Assigning user '.$user->id.' to player '.$model->id);
                    $model->setUser($user, false);
                }
                else if (!$user && $model->user && isset($_POST['user-name']))
                {
                    Yii::log('Removing user assignment from player '.$model->id);
                    $model->setUser(0, false);
                }
            }
            if($model->validate(null, false) && $model->save(false))
            {
                Yii::log('Updated player '.$model->id);
                Yii::app()->user->setFlash('player', Yii::t('mc', 'Player saved.'));
                $this->redirect(array('view','id'=>$model->id));
            }
        }
    
        require 'itemlist.php';
        $edit = @count($playerRoles) && Yii::app()->user->can($model->server_id, 'manage_players');
        $this->render('view',array(
            'model'=>$model,
            'itemlist'=>$itemlist,
            'viewDetails'=>Yii::app()->user->can($model->server_id, 'player_details'),
            'manage'=>Yii::app()->user->can($model->server_id, 'manage_players'),
            'give'=>Yii::app()->user->canSelf($model, 'give'),
            'tp'=>Yii::app()->user->canSelf($model, 'tp'),
            'edit'=>$edit,
            'sv'=>$model->server_id,
            'data'=>$this->ajaxRefresh($model, 'all'),
            'playerRoles'=>$playerRoles,
        ));
    }

    public function actionCreate($sv = false)
    {
        if (!Yii::app()->user->isSuperuser()
            && !Yii::app()->user->can($sv, 'manage_players', true))
            Yii::app()->user->deny();

        $server = Server::model()->findByPk((int)$sv);
        $model = new Player;
        if ($server)
            $model->server_id = $server->id;
        $model->level = 1;

        $playerRoles = $this->possiblePlayerRoles($model);
        if(isset($_POST['Player']))
        {
            if (Yii::app()->user->isSuperuser())
                $model->scenario = 'superuser';
            $model->attributes=$_POST['Player'];
            if (array_search($model->level, array_keys($playerRoles)) === false)
                $model->level = 0; //no permission
            $userName = Yii::app()->request->getPost('user-name', '');
            $user = User::model()->findByAttributes(array('name'=>$userName));
            if (!$user && @strlen($userName))
                $model->addError('user', Yii::t('mc', 'User not found'));
            else if ($user && array_search($user->getLevel($server->id), array_keys($playerRoles)) === false)
                $user = null;
            if($model->validate(null, false) && $model->save(false))
            {
                Yii::log('Created player '.$model->id);
                if ($user)
                    $model->user = $user;
                $this->redirect(array('view','id'=>$model->id));
            }
        }

        $this->render('view',array(
            'model'=>$model,
            'itemlist'=>array(),
            'viewDetails'=>true,
            'manage'=>true,
            'give'=>true,
            'tp'=>true,
            'edit'=>true,
            'sv'=>$server ? $server->id : false,

protected/views/player/admin.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->pageTitle = Yii::app()->name . ' - '.Yii::t('mc', 'Manage Players');

$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    Yii::t('mc', 'Players'),
);

$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Create Player'),
        'url'=>array('create'),
        'icon'=>'player_new',
    ),
    array(
        'label'=>Yii::t('mc', 'Back'),
        'url'=>array('server/index'),
        'icon'=>'back',
    ),
);

$this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'player-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'ajaxUpdate'=>false,
    'columns'=>array(
        array('name'=>'server_id', 'type'=>'raw',
            'value'=>'($s = Server::model()->findByPk($data->server_id)) ? CHtml::link(CHtml::encode($s->name), array("server/view", "id"=>$s->id)) : ""'),
        array('name'=>'name', 'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->name), array("player/view", "id"=>$data->id))'),
        array('name'=>'level','headerHtmlOptions'=>array('width'=>'90'),
            'value'=>'User::getRoleLabel(User::getLevelRole($data->level))'),
        array('name'=>'lastseen', 'value'=>'$data->lastseen ? @date("'.CJavaScript::quote(Yii::t('mc', 'd. M Y, H:i')).'", (int)$data->lastseen) : "'.CJavaScript::quote(Yii::t('mc', 'Never')).'"'),
        array('name'=>'banned','headerHtmlOptions'=>array('width'=>'30'),),
        'ip',
    ),
)); ?>

protected/views/player/index.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->pageTitle = Yii::app()->name . ' - '.Yii::t('mc', 'Player List');

$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    Server::model()->findByPk((int)$sv)->name=>array('server/view', 'id'=>$sv),
    Yii::t('mc', 'Players'),
);

$da = Yii::app()->params['show_delete_all_players'];
$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Create Player'),
        'url'=>array('create', 'sv'=>$sv),
        'icon'=>'player_new',
    ),
    array(
        'label'=>Yii::t('mc', 'Delete all Players'),
        'url'=>'#',
        'linkOptions'=>array(
            'submit'=>array('deleteAll', 'sv'=>$sv),
            'confirm'=>Yii::t('mc', 'Are you sure you want to delete ALL players?'),
            'csrf'=>true,
        ),
        'visible'=>((!$da || $da == 'superuser' || $da == 'user') && Yii::app()->user->isStaff()) || ($da == 'user'),
        'icon'=>'player_del',
    ),
    array(
        'label'=>Yii::t('mc', 'Manage Players'),
        'url'=>array('admin'),
        'visible'=>Yii::app()->user->isSuperuser(),
        'icon'=>'player',
    ),
    array(
        'label'=>Yii::t('mc', 'Back'),
        'url'=>array('server/view',
        'id'=>$sv),
        'icon'=>'back',
    ),
);
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'player-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'ajaxUpdate'=>false,
    'columns'=>array(
        array('name'=>'name', 'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->name), array("player/view", "id"=>$data->id))'),
        array('name'=>'level','headerHtmlOptions'=>array('width'=>'90'),
            'value'=>'$data->level == 1 ? Yii::t("mc", "Default Role") : User::getRoleLabel(User::getLevelRole($data->level))'),
        array('name'=>'lastseen', 'value'=>'$data->lastseen ? @date("'.CJavaScript::quote(Yii::t('mc', 'd. M Y, H:i')).'", (int)$data->lastseen) : "'.CJavaScript::quote(Yii::t('mc', 'Never')).'"'),
        'ip',
    ),
)); ?>

protected/views/player/view.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    $sv ? @Server::model()->findByPk((int)$sv)->name : Yii::t('mc', 'All')=>$sv ? array('server/view', 'id'=>$sv) : array('/server'),
);
if ($manage)
    $this->breadcrumbs[Yii::t('mc', 'Players')] = $sv ? array('player/index', 'sv'=>$sv) : array('player/admin');
$this->breadcrumbs[] = $model->isNewRecord ? Yii::t('mc', 'New Player') : $model->name;

if (!$model->isNewRecord)
{
$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Delete Player'),
        'url'=>'#',
        'linkOptions'=>array(
            'submit'=>array('delete', 'id'=>$model->id),
            'confirm'=>Yii::t('mc', 'Are you sure you want to delete this player?'),
            'csrf'=>true,
        ),
        'visible'=>$edit,
        'icon'=>'player_del',
    ),
);
}

$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>$manage ? ($sv ? array('player/index', 'sv'=>$sv) : array('player/admin')) : array('server/view', 'id'=>$sv),
    'icon'=>'back',
);

?>

<?php
if (!$edit)
{
    $attribs = array('name', 'level'=>array('name'=>'level',
        'value'=>User::getRoleLabel(User::getLevelRole($model->level))));
    $user = User::model()->findByPk((int)$model->user);
    if ($user)
        $attribs[] = array('label'=>Yii::t('mc', 'Belongs to'), 'type'=>'raw',
            'value'=>CHtml::encode($user->name));
}
else
{
    $form=$this->beginWidget('CActiveForm', array(
            'id'=>'player-form',
            'enableAjaxValidation'=>false,
        ));

    if (!$sv)
        $attribs[] = array('label'=>$form->labelEx($model,'server_id'), 'type'=>'raw',
                'value'=>$form->dropDownList($model,'server_id', CHtml::listData(Server::model()->findAll(),
                    'id', 'name')).' '.$form->error($model,'server_id'));
    $attribs[] = array('label'=>$form->labelEx($model,'name'), 'type'=>'raw',
            'value'=>$form->textField($model,'name').' '.$form->error($model,'name'));  
    $attribs[] = array('label'=>$form->labelEx($model,'level'), 'type'=>'raw',
            'value'=>$form->dropDownList($model,'level',$playerRoles)
            .' '.$form->error($model,'level'));
    $user = User::model()->findByPk($model->user);
    $assign = $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
        'name'=>'user-name',
        'source'=>$this->createUrl('user/autocomplete', array('server_id'=>$sv)),
        'value'=>@$_POST['user-name'] ? $_POST['user-name'] : ($user ? $user->name : ''),
        'options'=>array(
            'minLength'=>2,
        ),
    ), true);
    $assign .= $form->error($model, 'user');
    $attribs[] = array('label'=>Yii::t('mc', 'Assign to user'), 'type'=>'raw',
        'value'=>$assign);
    $attribs[] = array('label'=>$form->labelEx($model,'banned'), 'type'=>'raw',
            'value'=>$form->dropDownList($model, 'banned', array(''=>Yii::t('mc', 'False'), 'true'=>Yii::t('mc', 'True'))));
    $attribs[] = array('label'=>'', 'type'=>'raw', 'value'=>CHtml::submitButton($model->isNewRecord ? Yii::t('mc', 'Create') : Yii::t('mc', 'Save')));
}
if (!$model->isNewRecord)
{
    $attribs[] = 'status';
    $attribs[] = array('name'=>'lastseen', 'value'=>$model->lastseen ? @date(Yii::t('mc', 'd. M Y, H:i'), (int)$model->lastseen) : Yii::t('mc', 'Never'));
    if ($viewDetails)
        $attribs = array_merge($attribs, array('ip', 'previps', 'quitreason'));
}
if (@$give && $model->status == 'online')
{
    $defItem = '1:0';
    ob_start(); 
?>
        <div id="give-form">
        <?php
            $listdata = array();
            foreach ($itemlist as $idx => $item)
                $listdata[$idx] = $item['name'];
            asort($listdata);
            echo CHtml::dropDownList('give-item', $defItem, $listdata);
            $range = range(64, 1);
            echo CHtml::dropDownList('give-amount', @$defAmount, array_combine($range, $range));
         ?>
        <?php echo CHtml::ajaxButton(
            Yii::t('mc', 'Give'), '', array(
                    'type'=>'POST',
                    'data'=>array(
                        'ajax'=>'give',
                        'item'=>"js:$('#give-item').val()",
                        Yii::app()->request->csrfTokenName=>Yii::app()->request->csrfToken,
                        'amount'=>"js:$('#give-amount').val()"
                    ),
                    'success'=>'function(e) {if (e) alert(e);}'
                ),
                array('id'=>'give-button')
            ) ?>
        </div>

<?php
    $attribs[] = array('label'=>Yii::t('mc', 'Give'), 'type'=>'raw', 'value'=>ob_get_clean());
}

if (@$tp && $model->status == 'online')
{
    $attribs[] = array('label'=>Yii::t('mc', 'Teleport to'), 'type'=>'raw',
            'value'=>CHtml::tag('select', array('id'=>'tp-ajax'), $data['tp']).' '
            .CHtml::ajaxButton(Yii::t('mc', 'Teleport'), '', array(
                    'type'=>'POST',
                    'data'=>array(
                        'ajax'=>'tp',
                        Yii::app()->request->csrfTokenName=>Yii::app()->request->csrfToken,
                        'player'=>"js:$('#tp-ajax').val()"
                    ),
                    'success'=>'function(e) {if (e) alert(e);}'
                ),
                array('id'=>'teleport-button')
            ));
}

if (@$tp && $model->status == 'online')
{
    $attribs[] = array('label'=>Yii::t('mc', 'Summon'), 'type'=>'raw',
            'value'=>CHtml::tag('select', array('id'=>'summon-ajax'), $data['summon']).' '
            .CHtml::ajaxButton(Yii::t('mc', 'Summon'), '', array(
                    'type'=>'POST',
                    'data'=>array(
                        'ajax'=>'summon',
                        Yii::app()->request->csrfTokenName=>Yii::app()->request->csrfToken,
                        'player'=>"js:$('#summon-ajax').val()"
                    ),
                    'success'=>'function(e) {if (e) alert(e);}'
                ),
                array('id'=>'summon-button')
            ));
}


$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>$attribs,
)); 

if ($edit)
    $this->endWidget();
?>

<?php if(Yii::app()->user->hasFlash('player')): ?>
<div class="flash-success">
    <?php echo Yii::app()->user->getFlash('player'); ?>
</div>
<?php endif ?>

<?php if (!$model->isNewRecord) $this->printRefreshScript(); ?>