protected/models/Command.php
<?php
/**
 *
 *   Copyright © 2010-2019 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/

class Command extends ActiveRecord
{
/*
    int $id
    int $server_id
    string $name
    int $level
    int $prereq
    string $chat
    string $response
    string $run
    int $hidden
*/

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'command';
    }

    public function getDbConnection()
    {
        return Yii::app()->bridgeDb;
    }

    public function rules()
    {
        return array(
            array('name', 'required'),
            array('server_id', 'numerical', 'on'=>'superuser'),
            array('name', 'checkName'),
            array('level, prereq', 'numerical', 'integerOnly'=>true),
            array('chat, response, run, name', 'length', 'max'=>128),
            array('id, server_id, name, level, prereq, chat, response, run, hidden', 'safe', 'on'=>'search'),
            array('name, level, prereq, chat, response, run', 'safe', 'on'=>'serverSearch'),
            array('hidden', 'numerical', 'on'=>'superuser'),
            array('server_id', 'unsafe', 'on'=>'serverSearch'),
        );
    }

    public function checkName($attribute, $params)
    {
        $other = $this->findAllByAttributes(array('name'=>$this->name, 'server_id'=>$this->server_id));
        if (!count($other))
            return;
        if (count($other) > 1 || $other[0]->id != $this->id)
            $this->addError('name', Yii::t('mc', 'This name is already in use by another command.'));
    }

    public function relations()
    {
        return array(
            'server' => array(self::BELONGS_TO, 'server', 'server_id'),
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('mc', 'ID'),
            'server_id' => Yii::t('mc', 'Server'),
            'name' => Yii::t('mc', 'Name'),
            'level' => Yii::t('mc', 'Required Role'),
            'prereq' => Yii::t('mc', 'Prerequisite'),
            'chat' => Yii::t('mc', 'Chat'),
            'response' => Yii::t('mc', 'Response'),
            'run' => Yii::t('mc', 'Run'),
            'hidden' => Yii::t('mc', 'Hidden'),
        );
    }

    public function search()
    {
        $criteria=new CDbCriteria;

        $criteria->compare('`id`',$this->id);
        $criteria->compare('`server_id`',$this->server_id);
        $criteria->compare('`name`',$this->name,true);
        $criteria->compare('`level`',$this->level);
        $criteria->compare('`prereq`',$this->prereq);
        $criteria->compare('`chat`',$this->chat,true);
        $criteria->compare('`response`',$this->response,true);
        $criteria->compare('`run`',$this->run,true);
        if ($this->hasAttribute('hidden'))
            $criteria->compare('`hidden`',$this->hidden,false);

        return new CActiveDataProvider(get_class($this), array(
            'criteria'=>$criteria,
            'pagination'=>array('pageSize'=>20),
        ));
    }

    public function afterSave()
    {
        McBridge::get()->serverCmd($this->server_id, 'load command '.$this->id);
        return parent::afterSave();
    }

    public function afterDelete()
    {
        McBridge::get()->serverCmd($this->server_id, 'load command '.$this->id);
        return parent::afterDelete();
    }
}

protected/controllers/CommandController.php
<?php
/**
 *
 *   Copyright © 2010-2019 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/

class CommandController extends Controller
{
    public $layout='//layouts/column2';

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('index','view'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('create','update','delete','createDefault'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('admin'),
                'expression'=>'$user->isSuperuser()',
            ),
            array('deny',
                'users'=>array('*'),
            ),
        );
    }

    public function actionView($id)
    {
        $model = $this->loadModel($id);
        Yii::app()->user->can($model->server_id, 'view_command', true);
        if ($model->hasAttribute('hidden') && !Yii::app()->user->isSuperuser() && $model->hidden)
            Yii::app()->user->deny();

        if(isset($_POST['Command']) && Yii::app()->user->can($model->server_id, 'manage_commands'))
        {
            if (Yii::app()->user->isSuperuser())
                $model->scenario = 'superuser';
            $model->attributes=$_POST['Command'];
            if($model->save())
            {
                Yii::log('Updated command '.$model->id);
                Yii::app()->user->setFlash('command', Yii::t('mc', 'Command saved.'));
                $this->redirect(array('view','id'=>$model->id));
            }
        }
        $this->render('view',array(
            'model'=>$model,
            'edit'=>Yii::app()->user->can($model->server_id, 'manage_commands'),
            'sv'=>$model->server_id,
        ));
    }

    public function actionCreate($sv = false)
    {
        if (!Yii::app()->user->isSuperuser()
            && !Yii::app()->user->can($sv, 'manage_commands', true))
            Yii::app()->user->deny();

        $sv = (int)$sv;
        $model=new Command;
        $model->server_id = $sv;

        if(isset($_POST['Command']))
        {
            if (Yii::app()->user->isSuperuser())
                $model->scenario = 'superuser';
            $model->attributes=$_POST['Command'];
            if($model->save())
            {
                Yii::log('Created command '.$model->id);
                $this->redirect(array('view','id'=>$model->id));
            }
        }

        $this->render('view',array(
            'model'=>$model,
            'sv'=>$sv,
            'edit'=>true,
        ));
    }

    public function actionDelete($id)
    {
        if(Yii::app()->request->isPostRequest)
        {
            $model = $this->loadModel($id);
            $sv = $model->server_id;
            Yii::app()->user->can($model->server_id, 'manage_commands', true);
            if ($model->hasAttribute('hidden') && !Yii::app()->user->isSuperuser() && $model->hidden)
                Yii::app()->user->deny();
            Yii::log('Deleting command '.$model->id);
            $model->delete();

            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index', 'sv'=>$sv));
        }
        else
            throw new CHttpException(400, Yii::t('mc', 'Invalid request.'));
    }

    public function actionIndex($sv)
    {
        $sv = (int)$sv;
        Yii::app()->user->can($sv, 'manage_commands', true);
        $model=new Command(Yii::app()->user->isSuperuser() ? 'search' : 'serverSearch');
        $model->unsetAttributes();
        $model->server_id = $sv;
        if ($model->hasAttribute('hidden') && !Yii::app()->user->isSuperuser())
            $model->hidden = 0;
        if(isset($_GET['Command']))
            $model->attributes=$_GET['Command'];

        $this->render('index',array(
            'model'=>$model,
            'sv'=>$sv,
        ));
    }

    public function actionAdmin()
    {
        $model=new Command('search');
        $model->unsetAttributes();
        if(isset($_GET['Command']))
            $model->attributes=$_GET['Command'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    public function actionCreateDefault($sv)
    {
        if(!Yii::app()->request->isPostRequest)
            throw new CHttpException(400, Yii::t('mc', 'Invalid request.'));
        Yii::app()->user->can($sv, 'manage_commands', true);
        $server = Server::model()->findByPk((int)$sv);
        $server->createDefaultCommands();
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index', 'sv'=>$server->id));
    }

    public function loadModel($id)
    {
        $model=Command::model()->findByPk((int)$id);
        if($model===null)
            throw new CHttpException(404,Yii::t('mc', 'The requested page does not exist.'));
        return $model;
    }

    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='command-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/command/admin.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->pageTitle = Yii::app()->name.' - '.Yii::t('mc', 'Manage Commands');

$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    Yii::t('mc', 'Commands'),
);

$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Create Command'),
        'url'=>array('create'),
        'icon'=>'command_new',
    ),
    array(
        'label'=>Yii::t('mc', 'Back'),
        'url'=>array('server/index'),
        'icon'=>'back',
    ),
);


$this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'command-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'ajaxUpdate'=>false,
    'columns'=>array(
        array('name'=>'server_id', 'type'=>'raw',
            'value'=>'($s = Server::model()->findByPk($data->server_id)) ? CHtml::link(CHtml::encode($s->id." (".$s->name.")"), array("server/view", "id"=>$s->id)) : "0 (".Yii::t("mc", "Global").")"'),
        array('name'=>'name', 'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->name), array("command/view", "id"=>$data->id))'),
        array('name'=>'level','headerHtmlOptions'=>array('width'=>'90'),
            'value'=>'User::getRoleLabel(User::getLevelRole(@$data->level))'),
        'chat',
        'run',
    ),
)); ?>

protected/views/command/index.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->pageTitle = Yii::app()->name.' - '.Yii::t('mc', 'Command List');

$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    Server::model()->findByPk($sv)->name=>array('server/view', 'id'=>$sv),
    Yii::t('mc', 'Commands'),
);

$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Create Command'),
        'url'=>array('create', 'sv'=>$sv),
        'icon'=>'command_new',
    ),
    array(
        'label'=>Yii::t('mc', 'Manage Commands'),
        'url'=>array('admin'),
        'visible'=>Yii::app()->user->isSuperuser(),
        'icon'=>'command',
    ),
    array(
        'label'=>Yii::t('mc', 'Create Default Commands'),
        'url'=>'#',
        'linkOptions'=>array(
            'submit'=>array('createDefault', 'sv'=>$sv),
            'confirm'=>Yii::t('mc', 'Are you sure you want to create the default commands?'),
            'csrf'=>true,
        ),
        'icon'=>'command_new'
    ),
    array(
        'label'=>Yii::t('mc', 'Back'),
        'url'=>array('server/view', 'id'=>$sv),
        'icon'=>'back',
    ),
);
?>

<?php

$columns = array(
    array('name'=>'name', 'type'=>'raw',
        'value'=>'CHtml::link(CHtml::encode($data->name), array("command/view", "id"=>$data->id))'),
    array('name'=>'level',
        'value'=>'User::getRoleLabel(User::getLevelRole($data->level))'),
    'chat',
);

if ($model->hasAttribute('hidden'))
{
    $columns[] = array('name'=>'hidden', 'value'=>'$data->hidden ? "'.Yii::t('mc', 'Yes').'" :
        "'.Yii::t('mc', 'No').'"', 'htmlOptions'=>array('style'=>'width: 40px'),
        'visible'=>Yii::app()->user->isSuperuser());
}

$this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'command-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'ajaxUpdate'=>false,
    'columns'=>$columns,
)); ?>

protected/views/command/view.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->breadcrumbs=array(
    Yii::t('mc', 'Servers')=>array('server/index'),
    $sv ? @Server::model()->findByPk($sv)->name : Yii::t('mc', 'All')
        => $sv ? array('server/view', 'id'=>$sv) : array('/server'),
    Yii::t('mc', 'Commands')=>$sv ? array('command/index', 'sv'=>$sv) : array('command/admin'),
    $model->isNewRecord ? Yii::t('mc', 'New Command') : $model->name,
);

if (!$model->isNewRecord)
{
$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Delete Command'),
        'url'=>'#',
        'linkOptions'=>array(
            'submit'=>array('delete', 'id'=>$model->id),
            'confirm'=>Yii::t('mc', 'Are you sure you want to delete this item?'),
            'csrf'=>true,
        ),
        'visible'=>$edit,
        'icon'=>'command_del'
    ),
);
}
$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>($sv ? array('command/index', 'sv'=>$sv) : array('command/admin')),
    'icon'=>'back'
);
?>

<?php
if (!$edit)
{
    $attribs = array('name', 'level', 'prereq', 'chat', 'response', 'run');
}
else
{
    $form=$this->beginWidget('CActiveForm', array(
            'id'=>'command-form',
            'enableAjaxValidation'=>false,
        ));

    $userRoles = array_combine(User::$roleLevels, User::getRoleLabels());
    $userRoles[0] = Yii::t('mc', 'None');

    if (Yii::app()->user->isSuperuser())
    {
        $attribs[] = array('label'=>$form->labelEx($model,'server_id'), 'type'=>'raw',
            'value'=>$form->textField($model,'server_id').' '.$form->error($model,'server_id'),
            'hint'=>Yii::t('mc', 'The server ID, use 0 for "Global"'));
        $attribs[] = array('label'=>$form->labelEx($model,'hidden'), 'type'=>'raw',
                'value'=>$form->checkBox($model,'hidden')
                    .' '.$form->error($model,'hidden'),
                'hint'=>Yii::t('mc', 'Only show this command to other superusers'));
    }
    $attribs[] = array('label'=>$form->labelEx($model,'name'), 'type'=>'raw',
        'value'=>$form->textField($model,'name').' '.$form->error($model,'name'));
    $attribs[] = array('label'=>$form->labelEx($model,'level'), 'type'=>'raw',
        'value'=>$form->dropDownList($model,'level',$userRoles)
            .' '.$form->error($model,'level'));
    $attribs[] = array('label'=>$form->labelEx($model,'prereq'), 'type'=>'raw',
        'value'=>$form->dropDownList($model,'prereq',
            array('0'=>'None') + CHtml::listData(Command::model()->findAllByAttributes(
            array('server_id'=>$sv)), 'id', 'name'))
            .' '.$form->error($model,'prereq'),
        'hint'=>Yii::t('mc', 'This command has to be run before'));
    $attribs[] = array('label'=>$form->labelEx($model,'chat'), 'type'=>'raw',
        'value'=>$form->textField($model,'chat')
            .' '.$form->error($model,'chat'),
        'hint'=>Yii::t('mc', 'The users message has to begin with this'));
    $attribs[] = array('label'=>$form->labelEx($model,'response'), 'type'=>'raw',
        'value'=>$form->textField($model,'response')
            .' '.$form->error($model,'response'),
        'hint'=>Yii::t('mc', 'Whispered to the player'));
    $attribs[] = array('label'=>$form->labelEx($model,'run'), 'type'=>'raw',
        'value'=>$form->textField($model,'run')
            .' '.$form->error($model,'run'),
        'hint'=>Yii::t('mc', 'Run this Minecraft command (<a href="http://www.multicraft.org/site/page?view=usage#commands" target="_blank">see usage</a> for arguments and multiple commands)'));
    $attribs[] = array('label'=>'', 'type'=>'raw', 'value'=>CHtml::submitButton($model->isNewRecord ? Yii::t('mc', 'Create') : Yii::t('mc', 'Save')));
}

$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>$attribs,
)); 

if ($edit)
    $this->endWidget();
?>
<?php if(Yii::app()->user->hasFlash('command')): ?>
<div class="flash-success">
    <?php echo Yii::app()->user->getFlash('command'); ?>
</div>
<?php endif ?>