protected/controllers/UserController.php
<?php
/**
 *
 *   Copyright © 2010-2019 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/

class UserController extends Controller
{
    public $layout='//layouts/column2';
    var $attribs = array();
    var $role = '';

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('index', 'view', 'autocomplete'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('enableGauth', 'disableGauth'),
                'users'=>array('@'),
                'expression'=>'Yii::app()->params["enable_gauth"]',
            ),
            array('allow',
                'actions'=>array('create', 'update', 'delete'),
                'expression'=>'$user->isStaff()',
            ),
            array('allow',
                'actions'=>array('roles', 'editRole', 'resetRole'),
                'expression'=>'$user->isSuperuser() && Yii::app()->params["editable_roles"]',
            ),
            array('deny',
                'users'=>array('*'),
            ),
        );
    }

    public function actionView($id)
    {
        $id = (int)$id;
        if (!Yii::app()->user->isStaff() && (Yii::app()->params['hide_userlist'] === true)
            && (((int)Yii::app()->user->id) !== $id))
        {
            throw new CHttpException(403, Yii::t('mc', 'You are not authorized to perform this action.'));
        }
        $model = $this->loadModel($id);
        $model->scenario = Yii::app()->user->isSuperuser() ? 'superuserUpdate' : 'update';
        
        if (Yii::app()->user->isStaff())
            $model->sendData = isset($_POST['User']['sendData']) ? $_POST['User']['sendData'] : true;

        $staffEdit = Yii::app()->user->isStaff() && !in_array($model->global_role, array('superuser', 'staff'));
        $edit = Yii::app()->user->isSuperuser()
            || ($staffEdit && $model->name != Yii::app()->user->superuser)
            || (Yii::app()->user->name == $model->name);

        if(isset($_POST['User']) && $edit)
        {
            if (Yii::app()->params['demo_mode'] == 'enabled' && in_array($model->name, array('admin', 'owner', 'user')))
            {
                Yii::app()->user->setFlash('user', Yii::t('mc', 'Function disabled in demo mode.'));
                $this->redirect(array('view','id'=>$model->id));
            }
            if (Yii::app()->user->name !== Yii::app()->user->superuser
                    && $model->name == Yii::app()->user->superuser)
            {
                Yii::app()->user->setFlash('user', Yii::t('mc', 'Access Denied'));
                $this->redirect(array('view','id'=>$model->id));
            }
            $nameBackup = $model->name;
            $pwBackup = $model->password;
            $emailBackup = $model->email;
            $globalRoleBackup = $model->global_role;
            $themeBackup = $model->theme;
            $model->attributes=$_POST['User'];
            if (!strlen($_POST['User']['password']))
                $model->password = $pwBackup;
            if (Yii::app()->user->name == $model->name) // edit self, require confirmation for superuser as well
            {
                if (strlen($_POST['User']['password']) || $emailBackup != $model->email)
                {
                    if (!@strlen($_POST['oldPassword']))
                        $model->addError('oldPassword', Yii::t('mc', 'Enter current password to confirm the changes.'));
                    else if (!Yii::app()->user->verifyPassword($_POST['oldPassword']))
                        $model->addError('oldPassword', Yii::t('mc', 'Incorrect password'));
                }
                if (strlen($_POST['User']['password']) && $model->password != $model->confirmPassword)
                    $model->addError('confirmPassword', Yii::t('mc', 'New Password must be repeated exactly.'));
            }
            if (!(Yii::app()->user->isSuperuser() || $staffEdit) || $model->name == Yii::app()->user->superuser
                || $nameBackup == Yii::app()->user->superuser)
                $model->name = $nameBackup;
            if (!Yii::app()->user->isSuperuser())
                $model->global_role = $globalRoleBackup;
            if (!(Yii::app()->user->isSuperuser() || $staffEdit || Yii::app()->params['user_theme'] === true))
                $model->theme = $themeBackup;
            if($model->validate(null, false) && $model->save(false))
            {
                if (Yii::app()->user->isSuperuser() && isset($_POST['global_ftp_access']))
                {
                    $access = in_array($_POST['global_ftp_access'], array('ro', 'rw')) ? $_POST['global_ftp_access'] : '';
                    $model->setServerFtpAccess(0, $access);
                }
                Yii::log('Updated user '.$model->id);
                Yii::app()->user->setFlash('user', Yii::t('mc', 'User saved.'));
                $this->redirect(array('view','id'=>$model->id));
            }
        }
        else if (isset($_POST['action']) && (($edit && Yii::app()->params['user_api_keys'] === true) || Yii::app()->user->isSuperuser()))
        {
            switch ($_POST['action'])
            {
            case 'new_api_key':
                $model->generateApiKey();
                $model->save(false);
                Yii::log('Generated API key for user '.$model->id);
                Yii::app()->user->setFlash('user', Yii::t('mc', 'New API key generated.'));
                $this->redirect(array('view','id'=>$model->id));
                break;
            case 'del_api_key':
                $model->api_key = '';
                $model->save(false);
                Yii::log('Deleted API key for user '.$model->id);
                Yii::app()->user->setFlash('user', Yii::t('mc', 'API key deleted.'));
                $this->redirect(array('view','id'=>$model->id));
                break;
            }
        }
        $model->password = '';
        $model->confirmPassword = '';

        $allRoles = array_combine(User::$roles, User::getRoleLabels());
        $allRoles['staff'] = Yii::t('mc', 'Staff');
        $allRoles['superuser'] = Yii::t('mc', 'Superuser');

        $servers = array();
        $spp = 10;
        if (Yii::app()->user->isStaff())
        {
            if ($spp = Setting::model()->findByPk('serversPerPage'))
                $spp = max(1, (int)$spp->value);
            $sql = 'select `server_id` from `user_server` where `user_id`=? and `role`=\'owner\'';
            $cmd = Yii::app()->db->createCommand($sql);
            $cmd->bindValue(1, $model->id);
            $ids = $cmd->queryColumn();
            $servers = Server::model()->findAllByAttributes(array('id'=>array_values($ids)));
        }
        $this->render('view',array(
            'model'=>$model,
            'allRoles'=>$allRoles,
            'staffEdit'=>$staffEdit,
            'edit'=>$edit,
            'servers'=>new CArrayDataProvider($servers, array(
                'sort'=>array(
                    'attributes'=>array(
                        'name', 
                    ),
                ),
                'pagination'=>array('pageSize'=>$spp),
            )),
        ));
    }

    public function actionCreate()
    {
        $model=new User('create');
        $model->sendData = isset($_POST['User']['sendData']) ? $_POST['User']['sendData'] : true;
        $staffEdit = Yii::app()->user->isStaff() && !in_array($model->global_role, array('superuser', 'staff'));

        if(isset($_POST['User']))
        {
            $globalRoleBackup = $model->global_role;
            $model->attributes=$_POST['User'];
            if (!strlen($model->password) &&  Yii::app()->params['mail_welcome'])
                $model->password = substr(md5(rand().$model->name), 5, 13);
            if (!Yii::app()->user->isSuperuser())
                $model->global_role = $globalRoleBackup;
            if($model->save())
            {
                Yii::log('Created user '.$model->id);
                $this->redirect(array('view','id'=>$model->id));
            }
        }

        $allRoles = array_combine(User::$roles, User::getRoleLabels());
        $allRoles['staff'] = Yii::t('mc', 'Staff');
        $allRoles['superuser'] = Yii::t('mc', 'Superuser');

        $this->render('view',array(
            'model'=>$model,
            'allRoles'=>$allRoles,
            'staffEdit'=>$staffEdit,
            'edit'=>true,
        ));
    }

    public function actionDelete($id)
    {
        $model = $this->loadModel($id);
        if (Yii::app()->params['demo_mode'] == 'enabled' && in_array($model->name, array('admin', 'owner', 'user')))
        {
            Yii::app()->user->setFlash('user', Yii::t('mc', 'Function disabled in demo mode.'));
            $this->redirect(array('view','id'=>$model->id));
        }
        if(Yii::app()->request->isPostRequest)
        {
            if (!Yii::app()->user->isSuperuser() && in_array($model->global_role, array('superuser', 'staff')))
                throw new CHttpException(400,Yii::t('mc', 'Access Denied'));
            if ($model->name != Yii::app()->user->superuser)
            {
                Yii::log('Deleting user '.$model->id);
                $model->delete();   
            }

            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400, Yii::t('mc', 'Invalid request.'));
    }

    public function actionIndex()
    {
        if (!Yii::app()->user->isStaff() && Yii::app()->params['hide_userlist'])
            throw new CHttpException(403, Yii::t('mc', 'You are not authorized to perform this action.'));
        $model=new User(Yii::app()->user->isStaff() ? 'search' : 'userSearch');
        $model->unsetAttributes();
        if(isset($_GET['User']))

protected/views/user/_server.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$ajaxServerlist = false;
?>
<?php include dirname(__FILE__).'/../server/_view.php';

protected/views/user/disableGauth.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
if (Yii::app()->user->isStaff() || !Yii::app()->params['hide_userlist'])
    $this->breadcrumbs = array(Yii::t('mc', 'Users')=>array('index'));
else
    $this->breadcrumbs = array(Yii::t('mc', 'Profile'));
$this->breadcrumbs[$model->name] = array('view', 'id'=>$model->id);
$this->breadcrumbs[] = Yii::t('mc', 'Disable Google Authenticator');

$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>array('user/view', 'id'=>$model->id),
    'icon'=>'back'
);
?>

<?php
echo CHtml::beginForm();

if (Yii::app()->user->model->id === $model->id)
{
    $attribs[] = array('label'=>'', 'value'=>Yii::t('mc', 'Enter your password to disable Google Authenticator'));
    $attribs[] = array('label'=>Yii::t('mc', 'Confirm Panel Password'), 'type'=>'raw',
        'value'=>CHtml::activePasswordField($model, 'confirmPassword').' '.CHtml::error($model, 'confirmPassword'));
}
else
{
    $attribs[] = array('label'=>'', 'value'=>Yii::t('mc', 'Please confirm disabling Google Authenticator for this user'));
    echo CHtml::activeHiddenField($model, 'name');
}
$attribs[] = array('label'=>'', 'type'=>'raw', 'value'=>CHtml::submitButton(Yii::t('mc', 'Disable Google Authenticator')));

$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>$attribs,
)); 

echo CHtml::endForm();
?>

protected/views/user/editRole.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->breadcrumbs=array(
    Yii::t('mc', 'Users')=>array('index'),
    Yii::t('mc', 'Edit Roles')=>array('roles'),
    User::getRoleLabel($role),
);

Yii::app()->getClientScript()->registerCoreScript('jquery');

$this->menu[] = array(
    'label'=>Yii::t('mc', 'Reset'),
    'url'=>'#',
    'linkOptions'=>array(
        'submit'=>array('resetRole', 'role'=>$role),
        'confirm'=>Yii::t('mc', 'Reset this role to the default permissions?'),
        'csrf'=>true,
    ),
    'icon'=>'user_del',
);
$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>array('roles'),
    'icon'=>'back'
);
?>
<?php if(Yii::app()->user->hasFlash('user')): ?>
<div class="flash-success">
    <?php echo Yii::app()->user->getFlash('user'); ?>
</div>
<?php endif ?>
<h3><?php echo Yii::t('mc', 'Permissions for role "{role}"', array('{role}'=>User::getRoleLabel($role))) ?></h3>
<?php
echo CHtml::beginForm();
echo CHtml::hiddenField('role', $role);
$this->heading(Yii::t('mc', 'Server Status'));
$this->checkbox('get_status');
$this->checkbox('view');
$this->checkbox('get_players');
$this->checkbox('view_command');
$this->heading(Yii::t('mc', 'Backup'));
$this->checkbox('get_backup');
$this->checkbox('start_backup');
$this->checkbox('restore_backup');
$this->heading(Yii::t('mc', 'Chat'));
$this->checkbox('get_chat');
$this->checkbox('chat');
$this->checkbox('clear_chat');
$this->heading(Yii::t('mc', 'Console'));
$this->checkbox('get_log');
$this->checkbox('command');
$this->checkbox('clear_log');
$this->heading(Yii::t('mc', 'Players'));
$this->checkbox('view_player');
$this->checkbox('self_view_player');
$this->checkbox('player_details');
$this->checkbox('kick');
$this->checkbox('give');
$this->checkbox('tp');
$this->checkbox('self_give');
$this->checkbox('self_tp');
$this->heading(Yii::t('mc', 'Server Management'));
$this->checkbox('start');
$this->checkbox('stop');
$this->checkbox('restart');
$this->checkbox('edit');
$this->checkbox('edit_configs');
$this->checkbox('manage_commands');
$this->checkbox('manage_schedule');
$this->checkbox('manage_ftp');
$this->checkbox('manage_players');
$this->checkbox('manage_users');
$this->checkbox('manage_plugins');
$this->checkbox('manage_templates');
$this->checkbox('manage_mysql');
$this->checkbox('manage_params');
$this->saveButton();
echo CHtml::endForm();
?>

protected/views/user/enableGauth.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
if (Yii::app()->user->isStaff() || !Yii::app()->params['hide_userlist'])
    $this->breadcrumbs = array(Yii::t('mc', 'Users')=>array('index'));
else
    $this->breadcrumbs = array(Yii::t('mc', 'Profile'));
$this->breadcrumbs[$model->name] = array('view', 'id'=>$model->id);
$this->breadcrumbs[] = Yii::t('mc', 'Enable Google Authenticator');

$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>array('user/view', 'id'=>$model->id),
    'icon'=>'back'
);
?>

<?php
$attribs[] = array('label'=>'', 'value'=>Yii::t('mc', 'Scan the QR-Code below with your Google Authenticator app or enter the key manually'));
$attribs[] = array('label'=>Yii::t('mc', 'QR-Code'), 'type'=>'raw',
        'value'=>CHtml::image($qr, 'QR'));
$attribs[] = array('label'=>Yii::t('mc', 'Account Name'), 'value'=>$domain);
$attribs[] = array('label'=>Yii::t('mc', 'Key'), 'type'=>'raw',
        'value'=>CHtml::textField('', $secret, array('readonly'=>'readonly')));
$attribs[] = array('label'=>Yii::t('mc', 'Google Authenticator Code'), 'type'=>'raw',
        'value'=>CHtml::activeTextField($model, 'gauth_token').' '.CHtml::error($model, 'gauth_token'));
$attribs[] = array('label'=>Yii::t('mc', 'Confirm Panel Password'), 'type'=>'raw',
        'value'=>CHtml::activePasswordField($model, 'confirmPassword').' '.CHtml::error($model, 'confirmPassword'));
$attribs[] = array('label'=>'', 'type'=>'raw', 'value'=>CHtml::submitButton(Yii::t('mc', 'Enable Google Authenticator')));

echo CHtml::beginForm();

?>
<!-- Try to work around ignored autocomplete settings -->
<input type="text" style="position: absolute; top: -3px; width: 1px; height: 1px; border: 1px solid white"/>
<input type="password" style="position: absolute; top: -3px; width: 1px; height: 1px; border: 1px solid white" />
<?php

$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>$attribs,
)); 

echo CHtml::endForm();
?>

protected/views/user/index.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->pageTitle = Yii::app()->name . ' - '.Yii::t('mc', 'User List');

$this->breadcrumbs=array(
    Yii::t('mc', 'Users'),
);

$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'My Profile'),
        'url'=>array('user/view', 'id'=>Yii::app()->user->id),
        'icon'=>'user',
    ),
);
if (Yii::app()->user->isStaff())
{
    $this->menu[] =  array(
        'label'=>Yii::t('mc', 'Create User'),
        'url'=>array('create'),
        'icon'=>'user_new',
    );
}
if (@Yii::app()->params['editable_roles'] && Yii::app()->user->isSuperuser())
{
    $this->menu[] =  array(
        'label'=>Yii::t('mc', 'Edit Roles'),
        'url'=>array('roles'),
        'icon'=>'config',
    );
}
?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'user-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        array('name'=>'name', 'type'=>'raw',
            'value'=>'CHtml::link(CHtml::encode($data->name), array("user/view", "id"=>$data->id))'),
        array('name'=>'email', 'visible'=>Yii::app()->user->isStaff()),
        array('name'=>'global_role', 'value'=>'($data->name == Yii::app()->user->superuser ? "'.CJavaScript::quote(Yii::t('mc', 'Root Superuser')).'"'
            .' : User::getRoleLabel($data->global_role))', 'visible'=>Yii::app()->user->isStaff()),
        array('name'=>'lang', 'visible'=>Yii::app()->user->isStaff(), 'htmlOptions'=>array('width'=>20)),
    ),
)); ?>

protected/views/user/roles.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$this->breadcrumbs=array(
    Yii::t('mc', 'Users')=>array('index'),
    Yii::t('mc', 'Edit Roles'),
);

Yii::app()->getClientScript()->registerCoreScript('jquery');

$this->menu[] = array(
    'label'=>Yii::t('mc', 'Reset all'),
    'url'=>'#',
    'linkOptions'=>array(
        'submit'=>array('resetRole', 'role'=>'_all'),
        'confirm'=>Yii::t('mc', 'This will reset all roles to the default permissions, continue?'),
        'csrf'=>true,
    ),
    'icon'=>'user_del',
);
$this->menu[] = array(
    'label'=>Yii::t('mc', 'Back'),
    'url'=>array('user/index'),
    'icon'=>'back'
);

$attribs = array();
foreach (RolePermission::getRoles() as $k=>$v)
{
    $cmd = RolePermission::model()->dbConnection->createCommand('select count(*) from `role_permission` where `role`=:role');
    $perms = $cmd->queryScalar(array(':role'=>$k));
    $attribs[] = array(
        'id'=>$k,
        'link'=>CHtml::link(CHtml::encode($v), array('editRole', 'role'=>$k)),
        'perms'=>$perms,
    );
}
?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'role-grid',
    'dataProvider'=>new CArrayDataProvider($attribs),
    'columns'=>array(
        array('name'=>Yii::t('mc', 'Role'), 'type'=>'raw', 'value'=>'$data["link"]'),
        array('name'=>Yii::t('mc', 'Assigned Permissions'), 'type'=>'raw', 'value'=>'$data["perms"]'),
    ),
)); ?>

<?php if(Yii::app()->user->hasFlash('user')): ?>
<div class="flash-success">
    <?php echo Yii::app()->user->getFlash('user'); ?>
</div>
<?php endif ?>
<br/>
<br/>

protected/views/user/view.php
<?php
/**
 *
 *   Copyright © 2010-2018 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
if (Yii::app()->user->isStaff() || !Yii::app()->params['hide_userlist'])
    $this->breadcrumbs = array(Yii::t('mc', 'Users')=>array('index'));
else
    $this->breadcrumbs = array(Yii::t('mc', 'Profile'));
$this->breadcrumbs[] = $model->isNewRecord ? Yii::t('mc', 'New User') : $model->name;

Yii::app()->getClientScript()->registerCoreScript('jquery');

if (Yii::app()->user->isStaff()
    && $edit
    && !$model->isNewRecord
    && $model->name != Yii::app()->user->name
    && $model->name != Yii::app()->user->superuser)
{
$this->menu=array(
    array(
        'label'=>Yii::t('mc', 'Delete User'),
        'url'=>'#',
        'linkOptions'=>array(
            'submit'=>array('delete','id'=>$model->id),
            'confirm'=>Yii::t('mc', 'Are you sure you want to delete this user?'),
            'csrf'=>true,
        ),
        'icon'=>'user_del',
    ),
);
}
if ((Yii::app()->params['user_api_keys'] === true || Yii::app()->user->isSuperuser())  && !$model->isNewRecord)
{
    if (!$model->api_key)
    {
        $this->menu[] = array(
                'label'=>Yii::t('mc', 'Generate API Key'),
                'url'=>'#',
                'linkOptions'=>array(
                    'submit'=>array('view','id'=>$model->id),
                    'confirm'=>Yii::t('mc', 'Allow this user to access the Multicraft API?'),
                    'params'=>array('action'=>'new_api_key'),
                    'csrf'=>true,
                ),
                'icon'=>'key_new',
            );
    }
    else
    {
        $this->menu[] = array(
                'label'=>Yii::t('mc', 'Remove API Key'),
                'url'=>'#',
                'linkOptions'=>array(
                    'submit'=>array('view','id'=>$model->id),
                    'confirm'=>Yii::t('mc', 'Disable Multicraft API access for this user?'),
                    'params'=>array('action'=>'del_api_key'),
                    'csrf'=>true,
                ),
                'icon'=>'key_del',
            );
    }
}
if (!$model->isNewRecord && $model->id === Yii::app()->user->model->id && @Yii::app()->params['enable_gauth']
    && isset($model->gauth_secret) && !$model->gauth_secret)
{
    $this->menu[] = array(
            'label'=>Yii::t('mc', 'Enable Google Authenticator'),
            'url'=>array('user/enableGauth', 'id'=>$model->id),
            'icon'=>'key_new',
        );
}
else if ($model->gauthEnabled() && $edit)
{
    $this->menu[] = array(
            'label'=>Yii::t('mc', 'Disable Google Authenticator'),
            'url'=>array('user/disableGauth', 'id'=>$model->id),
            'icon'=>'key_del',
        );
}
if (Yii::app()->user->isStaff() || Yii::app()->params['hide_userlist'] !== true)
{
    $this->menu[] = array(
        'label'=>Yii::t('mc', 'Back'),
        'url'=>array('user/index'),
        'icon'=>'back'
    );
}
?>

<?php
if (!$edit)
{
    $attribs = array('name');
}
else
{
    $form=$this->beginWidget('CActiveForm', array(
            'id'=>'user-form',
            'enableAjaxValidation'=>false,
            'htmlOptions'=>array('autocomplete'=>'off'),
        ));

    if ($model->name != Yii::app()->user->superuser)
    {
        if (Yii::app()->user->isSuperuser() || $staffEdit)
        {
            $attribs[] = array('label'=>$form->labelEx($model,'name'), 'type'=>'raw',
                'value'=>$form->textField($model,'name').' '.$form->error($model,'name'));
        }
        if (Yii::app()->user->isSuperuser())
        {
            $attribs[] = array('label'=>$form->labelEx($model,'global_role'), 'type'=>'raw',
                'value'=>$form->dropDownList($model,'global_role',$allRoles)
                    .' '.$form->error($model,'global_role'),
                'hint'=>Yii::t('mc', 'Role that applies for all servers'));
        }
    }
    else
    {
        $attribs[] = 'name';
        $attribs[] = ['label'=>$model->getAttributeLabel('global_role'), 'value'=>Yii::t('mc', 'Superuser')];
    }
    if (Yii::app()->user->isSuperuser())
    {
        $options = array(
            ''      => Yii::t('mc', 'None'),
            'ro'    => Yii::t('mc', 'Read only'),
            'rw'    => Yii::t('mc', 'Full access')
        );
        $access = isset($_POST['global_ftp_access']) ? $_POST['global_ftp_access'] : $model->getServerFtpAccess(0);
        $attribs[] = array('label'=>Yii::t('mc', 'Global FTP Access'), 'type'=>'raw',
            'value'=>CHtml::dropDownList('global_ftp_access', $access, $options));
    }
    if ($model->api_key)
        $attribs[] = array('label'=>$form->labelEx($model,'api_key'), 'type'=>'raw',
                'value'=>CHtml::textField('ak', $model->api_key, array('id'=>'apiKeyBox', 'readonly'=>'readonly')).' '.$form->error($model,'api_key'));
    $attribs[] = array('label'=>$form->labelEx($model,'lang'), 'type'=>'raw',
            'value'=>$form->dropDownList($model,'lang', $this->languageSelection()).' '.$form->error($model,'lang'));
    if (Yii::app()->params['user_theme'] === true)
    {
        $attribs[] = array('label'=>$form->labelEx($model,'theme'), 'type'=>'raw',
                'value'=>$form->dropDownList($model,'theme', $this->themeSelection()).' '.$form->error($model,'theme'));
    }
    $attribs[] = array('label'=>$form->labelEx($model,'email'), 'type'=>'raw',
            'value'=>$form->textField($model,'email').' '.$form->error($model,'email'));
    if (Yii::app()->user->name == $model->name)
    {
        $attribs[] = array('label'=>CHtml::label(Yii::t('mc', 'Current Password'), 'oldPassword'), 'type'=>'raw',
                'value'=>CHtml::passwordField('oldPassword', '').' '.$form->error($model,'oldPassword'));
        $attribs[] = array('label'=>CHtml::label(Yii::t('mc', 'New Password'), 'User_password'), 'type'=>'raw',
                'value'=>$form->passwordField($model,'password').' '.$form->error($model,'password'));
        $attribs[] = array('label'=>$form->labelEx($model,'confirmPassword'), 'type'=>'raw',
                'value'=>$form->passwordField($model,'confirmPassword').' '.$form->error($model,'confirmPassword'));
    }
    else
    {
        $attribs[] = array('label'=>$form->labelEx($model,'password'), 'type'=>'raw',
                'value'=>$form->passwordField($model,'password').' '.$form->error($model,'password'));
    }
    if (Yii::app()->user->isStaff() && Yii::app()->params['mail_welcome'])
    {
        $attribs[] = array('label'=>CHtml::label($model->isNewRecord ? Yii::t('mc', 'Send Welcome Mail')
                : Yii::t('mc', 'Send new password if changed'), 'User_sendData'), 'type'=>'raw',
            'value'=>$form->checkBox($model, 'sendData'));
    }
    $attribs[] = array('label'=>'', 'type'=>'raw', 'value'=>CHtml::submitButton($model->isNewRecord ? Yii::t('mc', 'Create') : Yii::t('mc', 'Save')));
}


$this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>$attribs,
)); 

if ($edit)
    $this->endWidget();

echo CHtml::script('$("#apiKeyBox").focus(function() { this.select(); });');            
?>

<?php if(Yii::app()->user->hasFlash('user')): ?>
<div class="flash-success">
    <?php echo Yii::app()->user->getFlash('user'); ?>
</div>
<?php endif ?>
<br/>
<br/>
<?php
if (!$model->isNewRecord)
{
    $this->widget('zii.widgets.CListView', array(
        'emptyText'=>'',
        'dataProvider'=>$servers,
        'itemView'=>'_server',
        'ajaxUpdate'=>false,
        'sortableAttributes'=>array(
            'name'=>Yii::t('mc', 'Name'),
        ),
    ));
}